connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: andrew
  password: andrew

development:
  <<: *connection
  database: prelangpg01_development

test:
  <<: *connection
  database: prelangpg01_test

production:
  <<: *connection
  database: prelangpg01_production